pygments: true
markdown: kramdown
permalink: /:categories/:year/:month/:title/
pagination: 5

exclude: [
    '.gems',
    '.gitignore',
    '.settings.xml',
    '.slugignore',
    'MylesBraithwaite.com.tmproj',
    'README.mdown',
    'Rakefile',
    'TODO.txt',
    'config.ru'
]

lessc: /usr/bin/lessc