pygments: true
markdown: kramdown
permalink: /:categories/:year/:month/:title/
pagination: 5

exclude: [
    'Rakefile',
    'README.mdown',
    'MylesBraithwaite.com.tmproj',
    'config.ru',
    'TODO.txt'
]
