pygments: true
markdown: kramdown
permalink: /:categories/:year/:month/:title/
pagination: 5

exclude: [
    '.gems',
    '.gitignore',
    '.settings.xml',
    '.slugignore',
    'MylesBraithwaite.com.tmproj',
    'README.mdown',
    'Rakefile',
    'TODO.txt',
    'config.ru',
    'media/uploads'
]

lessc: /usr/bin/lessc

category_title_prefix: "Archive for "
tag_title_prefix: "Archvie for "

kramdown:
    auto_ids: true
    footnote_nr: 1
